// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by $AppName$ $AppVersion$
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_caption_parallax(i,h,d,g,e,a){var c=jQuery;h.parent().css({position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"});h.html(g).css("width","100%").stop(1,1);d.html(e).css("width","100%").stop(1,1);function f(l,m,n){var j=new Date()*1;var k=function(){var o=(new Date()*1-j)/m;if(o>=1){l(1);cancelAnimationFrame(k);if(n){n()}}else{l(o);requestAnimationFrame(k)}};k()}(function b(o,k,w,s,t,x){var q=15;var n=i.$this.width();q*=n/100;function r(A,B){return A.css(i.support.transform?{transform:"translate3d("+B+"px,0px,0px)"}:{marginLeft:B}).css("display","inline-block")}if(i.prevIdx==i.curIdx){r(o,0).fadeIn(t/3);r(c(">div,>span",o),0)}else{var m=c(">div",o);var z=c(">div",k);var p=c(">span",o);var j=c(">span",k);var v=q+n*(x?-1:1),y=q+n*(x?1:-1),u=(x?-1:1)*q;r(o,v).show();r(k,0).show();r(m,u);r(z,0);r(p,2*u);r(j,0);f(function(A){A=c.easing.swing(A);r(o,(1-A)*v);r(k,A*y)},i.duration);var l=0.8;f(function(A){A*=l;r(p,(1-A)*2*u);r(m,(1-A)*u);r(j,A*(-2*u));r(z,A*(-u))},i.duration,function(){f(function(A){A=c.easing.easeOutCubic(1,A,0,1,1,1);var B=(1-l)*2*u,D=(1-l)*u,C=l*(-2*u),E=l*(-u);r(p,(1-A)*B);r(m,(1-A)*D);r(j,(1-A)*C+A*(-2*u));r(z,(1-A)*E+A*(-u))},(/Firefox/g.test(navigator.userAgent)?1500:i.delay))})}}(h,d,g,e,i.captionDuration,a))};