

<link rel="stylesheet" href="../bootstrap-3.2.0-dist/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="../bootstrap-3.2.0-dist/css/bootstrap-theme.min.css">
<script src="../bootstrap-3.2.0-dist/js/jquery-1.11.1.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="../bootstrap-3.2.0-dist/js/bootstrap.min.js"></script>


<link href="../css/style.css" rel="stylesheet" />



<?php
include '../include/config.php'; 
	$folder='../_index';
	if(isset($_GET['folder']))
   $folder = $_GET['folder'];
   include '../_menu/index.php'; 

		
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Image carousel generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Image carousel" />
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>

	<!-- End WOWSlider.com HEAD section -->
</head>
<div class="col-md-3">
<?php include '../include/_sidebar.php';?>
</div>

<div class="col-md-9">



<body style="background-color:#ffffff;margin:auto">
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/kodaer.jpg" alt="kodaer" title="kodaer" id="wows1_0"/></li>
<li><img src="data1/images/bhajipala1480x320.jpg" alt="bhajipala1-480x320" title="bhajipala1-480x320" id="wows1_1"/></li>
<li><a href="http://wowslider.com/vf"><img src="data1/images/sd_l_2012829172730.jpg" alt="full screen slider" title="sd_L_2012829172730" id="wows1_2"/></a></li>
<li><img src="data1/images/veggies.jpg" alt="Veggies" title="Veggies" id="wows1_3"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="kodaer"><img src="data1/tooltips/kodaer.jpg" alt="kodaer"/>1</a>
<a href="#" title="bhajipala1-480x320"><img src="data1/tooltips/bhajipala1480x320.jpg" alt="bhajipala1-480x320"/>2</a>
<a href="#" title="sd_L_2012829172730"><img src="data1/tooltips/sd_l_2012829172730.jpg" alt="sd_L_2012829172730"/>3</a>
<a href="#" title="Veggies"><img src="data1/tooltips/veggies.jpg" alt="Veggies"/>4</a>
</div></div><span class="wsl"><a href="http://wowslider.com/vu">image carousel</a> by WOWSlider.com v6.7</span>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
    <br />
  <h2><center><b>Products Available in Stocks</b></center></h2>  
    
    <div class="row">
     <?php

$con = mysqli_connect('localhost','root','','dbshopping') or die(mysqli_error($con));
$q = mysqli_query($con,'select * from tblproduct');

	while($r = mysqli_fetch_array($q))
	{
		extract($r);
  ?>
  
<div class="col-sm-6 col-md-3">
<div class="thumbnail">

<div class="caption" align="center">
<img width="160px" height="160px" class="img img-thumbnail" src="../admin/_uploadproduct/photos/<?=$product_id?>.png" >
<b><?=$product_name?></b>

</div>
</div>
</div>
<?php
}
?>
</div>
</body>

</div>
<div class="col-md-12">
<div class="footer" style="background-color:#0F6" >
<?php include '../include/_footer.php';?>
</div></div>
</html>

