// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by $AppName$ $AppVersion$
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_rotate(j,i,a){var d=jQuery;var h=d(this);var e=d(".ws_list",a);var b={position:"absolute",left:0,top:0};var f=d("<div>").addClass("ws_effect ws_rotate").css(b).css({height:"100%",width:"100%",overflow:"hidden"}).appendTo(a.parent());var c;function g(n,k,l,m){if(j.support.transform&&j.support.transition){k.transform="translate3d(0,0,0) rotate("+k.rotate+"deg) scale("+k.scale+")";delete k.scale;delete k.rotate;if(l){k.transition="all "+l+"ms cubic-bezier(0.770, 0.000, 0.175, 1.000)"}n.css(k);if(m){n.on("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",function(){m()})}}else{if(l){n.animate(k,{easing:"easeInOutExpo",duration:j.duration,complete:m?m:0})}else{n.css(k)}}}this.go=function(k,l){var n=d(i[0]);n={width:n.width(),height:n.height(),marginTop:parseFloat(n.css("marginTop")),marginLeft:parseFloat(n.css("marginLeft"))};if(c){c.stop(true,true)}c=d(i.get(k)).clone().css(b).css(n).hide().appendTo(f);if(!j.noCross){var m=d(i.get(l)).clone().css(b).css(n).appendTo(f);g(c,{opacity:1,rotate:0,scale:1});setTimeout(function(){e.hide();g(m,{rotate:j.rotateOut||180,scale:j.scaleOut||10,opacity:0},j.duration,function(){m.remove()})},0)}g(c,{display:"block",opacity:0,rotate:-(j.rotateIn||180),scale:j.scaleIn||10,zIndex:10});setTimeout(function(){g(c,{rotate:0,scale:1,opacity:1},j.duration,function(){c.remove();c=0;h.trigger("effectEnd")})},0)}};